### ISSUE TITLE
프로모션 페이지 (혹은 다른 페이지) 에서 프로필, 새 글 쓰기 가 안보이는 이슈

### ISSUE THREAD

**Issue by KyungJunNoh** [Frame-in-Puzzle/Puzzle-Front#90]
## Puzzle에서 이런 문제가 발생했어요!
<img width="2038" alt="2022-06-18_17-09-46" src="https://user-images.githubusercontent.com/68670670/174429060-c9b7cbe2-0566-46df-af88-25ee4b39b9c8.png">

가끔 오른쪽위의 프로필, 새 글 쓰기가 보이지 않는 이슈가 있습니다.
장기간 미접속 하다가 접속했을때 토큰이 리프레시되지 않아서 안보이는 것 같은데 확인부탁드려요

**Comment by ImChangGyu** [comment]
넵 그래서 현재 오른쪽 위의 nav의 경우는 token refresh를 우선으로 하고 refresh에 실패할 경우 로그인 버튼이 뜨도록 error를 핸들링 했습니다.
