### ISSUE TITLE
프로필 업데이트 후 업데이트 된것을 알 수 있는 수단이 필요

### ISSUE THREAD

**Issue by KyungJunNoh** [Frame-in-Puzzle/Puzzle-Front#91]
## Puzzle에서 이런 문제가 발생했어요!
<img width="1695" alt="2022-06-18_17-12-24" src="https://user-images.githubusercontent.com/68670670/174429113-85634e14-6df5-429b-b256-23ff46ef1a93.png">

프로필 업데이트 후 업데이트가 되었다는 것을 알릴 수 있는 수단이 필요해보입니다.
(ex : react-toastify 라이브러리)

**Comment by ImChangGyu** [comment]
네 좋은 의견 감사합니다.
현재 프로필을 업데이트 한 이후 toast 메시지를 이용해 수정이 되었음을 알리고 메인페이지로 리다이렉션 되게 되었습니다!
